// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Vigia.Datos.Persistencia;

#nullable disable

namespace Vigia.Datos.Migraciones
{
    [DbContext(typeof(VigiaDbContext))]
    partial class VigiaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Vigia.Datos.Persistencia.AgregadoDia", b =>
                {
                    b.Property<Guid>("MonitorId")
                        .HasColumnType("uuid")
                        .HasColumnName("monitor_id");

                    b.Property<DateTimeOffset>("Periodo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("periodo");

                    b.Property<int>("Comprobaciones")
                        .HasColumnType("integer")
                        .HasColumnName("comprobaciones");

                    b.Property<int>("Correctas")
                        .HasColumnType("integer")
                        .HasColumnName("correctas");

                    b.Property<int>("EnMantenimiento")
                        .HasColumnType("integer")
                        .HasColumnName("en_mantenimiento");

                    b.Property<int>("Fallidas")
                        .HasColumnType("integer")
                        .HasColumnName("fallidas");

                    b.Property<double?>("LatenciaMediaMs")
                        .HasColumnType("double precision")
                        .HasColumnName("latencia_media_ms");

                    b.Property<double?>("PeorP95HoraMs")
                        .HasColumnType("double precision")
                        .HasColumnName("peor_p95hora_ms");

                    b.Property<double>("SegCaido")
                        .HasColumnType("double precision")
                        .HasColumnName("seg_caido");

                    b.Property<double>("SegDegradado")
                        .HasColumnType("double precision")
                        .HasColumnName("seg_degradado");

                    b.Property<double>("SegDesconocido")
                        .HasColumnType("double precision")
                        .HasColumnName("seg_desconocido");

                    b.Property<double>("SegMantenimiento")
                        .HasColumnType("double precision")
                        .HasColumnName("seg_mantenimiento");

                    b.Property<double>("SegOperativo")
                        .HasColumnType("double precision")
                        .HasColumnName("seg_operativo");

                    b.Property<double>("SegSospechoso")
                        .HasColumnType("double precision")
                        .HasColumnName("seg_sospechoso");

                    b.HasKey("MonitorId", "Periodo")
                        .HasName("pk_resultados_dia");

                    b.ToTable("resultados_dia", (string)null);
                });

            modelBuilder.Entity("Vigia.Datos.Persistencia.AgregadoHora", b =>
                {
                    b.Property<Guid>("MonitorId")
                        .HasColumnType("uuid")
                        .HasColumnName("monitor_id");

                    b.Property<DateTimeOffset>("Periodo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("periodo");

                    b.Property<int>("Comprobaciones")
                        .HasColumnType("integer")
                        .HasColumnName("comprobaciones");

                    b.Property<int>("Correctas")
                        .HasColumnType("integer")
                        .HasColumnName("correctas");

                    b.Property<int>("EnMantenimiento")
                        .HasColumnType("integer")
                        .HasColumnName("en_mantenimiento");

                    b.Property<int>("Fallidas")
                        .HasColumnType("integer")
                        .HasColumnName("fallidas");

                    b.Property<double?>("LatenciaMediaMs")
                        .HasColumnType("double precision")
                        .HasColumnName("latencia_media_ms");

                    b.Property<double?>("P50Ms")
                        .HasColumnType("double precision")
                        .HasColumnName("p50ms");

                    b.Property<double?>("P95Ms")
                        .HasColumnType("double precision")
                        .HasColumnName("p95ms");

                    b.Property<double>("SegCaido")
                        .HasColumnType("double precision")
                        .HasColumnName("seg_caido");

                    b.Property<double>("SegDegradado")
                        .HasColumnType("double precision")
                        .HasColumnName("seg_degradado");

                    b.Property<double>("SegDesconocido")
                        .HasColumnType("double precision")
                        .HasColumnName("seg_desconocido");

                    b.Property<double>("SegMantenimiento")
                        .HasColumnType("double precision")
                        .HasColumnName("seg_mantenimiento");

                    b.Property<double>("SegOperativo")
                        .HasColumnType("double precision")
                        .HasColumnName("seg_operativo");

                    b.Property<double>("SegSospechoso")
                        .HasColumnType("double precision")
                        .HasColumnName("seg_sospechoso");

                    b.HasKey("MonitorId", "Periodo")
                        .HasName("pk_resultados_hora");

                    b.HasIndex("Periodo")
                        .HasDatabaseName("ix_resultados_hora_periodo");

                    b.ToTable("resultados_hora", (string)null);
                });

            modelBuilder.Entity("Vigia.Datos.Persistencia.CambioDeEstadoEntidad", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<short>("Anterior")
                        .HasColumnType("smallint")
                        .HasColumnName("anterior");

                    b.Property<DateTimeOffset>("Momento")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("momento");

                    b.Property<Guid>("MonitorId")
                        .HasColumnType("uuid")
                        .HasColumnName("monitor_id");

                    b.Property<short>("Nuevo")
                        .HasColumnType("smallint")
                        .HasColumnName("nuevo");

                    b.HasKey("Id")
                        .HasName("pk_cambios_estado");

                    b.HasIndex("MonitorId", "Momento")
                        .HasDatabaseName("ix_cambios_estado_monitor_id_momento");

                    b.ToTable("cambios_estado", (string)null);
                });

            modelBuilder.Entity("Vigia.Datos.Persistencia.ResultadoEntidad", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("Momento")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("momento");

                    b.Property<bool>("Correcto")
                        .HasColumnType("boolean")
                        .HasColumnName("correcto");

                    b.Property<string>("Detalles")
                        .HasColumnType("jsonb")
                        .HasColumnName("detalles");

                    b.Property<bool>("EnMantenimiento")
                        .HasColumnType("boolean")
                        .HasColumnName("en_mantenimiento");

                    b.Property<string>("Error")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("error");

                    b.Property<short>("Fallo")
                        .HasColumnType("smallint")
                        .HasColumnName("fallo");

                    b.Property<int>("LatenciaMs")
                        .HasColumnType("integer")
                        .HasColumnName("latencia_ms");

                    b.Property<Guid>("MonitorId")
                        .HasColumnType("uuid")
                        .HasColumnName("monitor_id");

                    b.HasKey("Id", "Momento")
                        .HasName("pk_resultados");

                    b.ToTable("resultados", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Vigia.Datos.Persistencia.SeguimientoEntidad", b =>
                {
                    b.Property<Guid>("MonitorId")
                        .HasColumnType("uuid")
                        .HasColumnName("monitor_id");

                    b.Property<DateTimeOffset>("Desde")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("desde");

                    b.Property<short>("Estado")
                        .HasColumnType("smallint")
                        .HasColumnName("estado");

                    b.Property<int>("FallosSeguidos")
                        .HasColumnType("integer")
                        .HasColumnName("fallos_seguidos");

                    b.Property<Guid?>("IncidenteAbiertoId")
                        .HasColumnType("uuid")
                        .HasColumnName("incidente_abierto_id");

                    b.Property<DateTimeOffset?>("UltimaObservacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ultima_observacion");

                    b.HasKey("MonitorId")
                        .HasName("pk_seguimientos");

                    b.HasIndex("IncidenteAbiertoId")
                        .HasDatabaseName("ix_seguimientos_incidente_abierto_id");

                    b.ToTable("seguimientos", (string)null);
                });

            modelBuilder.Entity("Vigia.Dominio.Mantenimiento.VentanaMantenimiento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("Fin")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fin");

                    b.Property<DateTimeOffset>("Inicio")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("inicio");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("motivo");

                    b.PrimitiveCollection<Guid[]>("_monitorIds")
                        .IsRequired()
                        .HasColumnType("uuid[]")
                        .HasColumnName("monitor_ids");

                    b.HasKey("Id")
                        .HasName("pk_ventanas_mantenimiento");

                    b.HasIndex("Fin")
                        .HasDatabaseName("ix_ventanas_mantenimiento_fin");

                    b.ToTable("ventanas_mantenimiento", (string)null);
                });

            modelBuilder.Entity("Vigia.Dominio.Monitores.Grupo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.Property<bool>("Publico")
                        .HasColumnType("boolean")
                        .HasColumnName("publico");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("slug");

                    b.HasKey("Id")
                        .HasName("pk_grupos");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_grupos_slug");

                    b.ToTable("grupos", (string)null);
                });

            modelBuilder.Entity("Vigia.Dominio.Monitores.Monitor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<string>("Configuracion")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("configuracion");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en");

                    b.Property<int>("FallosParaIncidente")
                        .HasColumnType("integer")
                        .HasColumnName("fallos_para_incidente");

                    b.Property<Guid?>("GrupoId")
                        .HasColumnType("uuid")
                        .HasColumnName("grupo_id");

                    b.Property<TimeSpan>("Intervalo")
                        .HasColumnType("interval")
                        .HasColumnName("intervalo");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.Property<TimeSpan?>("UmbralLento")
                        .HasColumnType("interval")
                        .HasColumnName("umbral_lento");

                    b.HasKey("Id")
                        .HasName("pk_monitores");

                    b.HasIndex("Activo")
                        .HasDatabaseName("ix_monitores_activo");

                    b.HasIndex("GrupoId")
                        .HasDatabaseName("ix_monitores_grupo_id");

                    b.ToTable("monitores", (string)null);
                });

            modelBuilder.Entity("Vigia.Dominio.Seguimiento.Incidente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("AbiertoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("abierto_en");

                    b.Property<string>("Causa")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("causa");

                    b.Property<DateTimeOffset?>("CerradoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cerrado_en");

                    b.Property<short?>("CerradoPor")
                        .HasColumnType("smallint")
                        .HasColumnName("cerrado_por");

                    b.Property<int>("Fallos")
                        .HasColumnType("integer")
                        .HasColumnName("fallos");

                    b.Property<Guid>("MonitorId")
                        .HasColumnType("uuid")
                        .HasColumnName("monitor_id");

                    b.HasKey("Id")
                        .HasName("pk_incidentes");

                    b.HasIndex("MonitorId")
                        .IsUnique()
                        .HasDatabaseName("ux_incidentes_un_abierto_por_monitor")
                        .HasFilter("cerrado_en IS NULL");

                    b.HasIndex("MonitorId", "AbiertoEn")
                        .HasDatabaseName("ix_incidentes_monitor_id_abierto_en");

                    b.ToTable("incidentes", (string)null);
                });

            modelBuilder.Entity("Vigia.Datos.Persistencia.AgregadoDia", b =>
                {
                    b.HasOne("Vigia.Dominio.Monitores.Monitor", null)
                        .WithMany()
                        .HasForeignKey("MonitorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_resultados_dia_monitores_monitor_id");
                });

            modelBuilder.Entity("Vigia.Datos.Persistencia.AgregadoHora", b =>
                {
                    b.HasOne("Vigia.Dominio.Monitores.Monitor", null)
                        .WithMany()
                        .HasForeignKey("MonitorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_resultados_hora_monitores_monitor_id");
                });

            modelBuilder.Entity("Vigia.Datos.Persistencia.CambioDeEstadoEntidad", b =>
                {
                    b.HasOne("Vigia.Dominio.Monitores.Monitor", null)
                        .WithMany()
                        .HasForeignKey("MonitorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_cambios_estado_monitores_monitor_id");
                });

            modelBuilder.Entity("Vigia.Datos.Persistencia.SeguimientoEntidad", b =>
                {
                    b.HasOne("Vigia.Dominio.Seguimiento.Incidente", null)
                        .WithMany()
                        .HasForeignKey("IncidenteAbiertoId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_seguimientos_incidentes_incidente_abierto_id");

                    b.HasOne("Vigia.Dominio.Monitores.Monitor", null)
                        .WithOne()
                        .HasForeignKey("Vigia.Datos.Persistencia.SeguimientoEntidad", "MonitorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_seguimientos_monitores_monitor_id");
                });

            modelBuilder.Entity("Vigia.Dominio.Monitores.Monitor", b =>
                {
                    b.HasOne("Vigia.Dominio.Monitores.Grupo", null)
                        .WithMany()
                        .HasForeignKey("GrupoId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_monitores_grupos_grupo_id");
                });

            modelBuilder.Entity("Vigia.Dominio.Seguimiento.Incidente", b =>
                {
                    b.HasOne("Vigia.Dominio.Monitores.Monitor", null)
                        .WithMany()
                        .HasForeignKey("MonitorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_incidentes_monitores_monitor_id");
                });
#pragma warning restore 612, 618
        }
    }
}
